
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricomrdnsyh
 */
public class PanelPeminjaman extends javax.swing.JPanel {

    /**
     * Creates new form PanelPeminjaman
     */
    public static String id = "";
    public PanelPeminjaman() {
        initComponents();
    }
    void kosong(){
        txtLembaga.setText("");
        txtPeminjam.setText("");
        txtHP.setText("");
        txaDeskripsi.setText("");
        txtTujuan.setText("");
        cboRuangan.setSelectedIndex(0);
        txtacara.setText("");
        txtJumlah.setText("");
        dtPeminjaman.setDateFormatString("");
        dtSelesai.setDateFormatString("");
        txtJam.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtLembaga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPeminjam = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtJam = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cboRuangan = new javax.swing.JComboBox<>();
        txtacara = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dtSelesai = new com.toedter.calendar.JDateChooser();
        dtPeminjaman = new com.toedter.calendar.JDateChooser();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDeskripsi = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(58, 79, 122));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Peminjaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(408, 408, 408))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(58, 79, 122));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-go-next-icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel11.setText("WIB");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(710, 260, 30, 30);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(20, 190, 420, 2);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(20, 40, 2, 150);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(440, 40, 2, 150);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(20, 40, 420, 2);

        jLabel12.setText("Nama Lembaga / Organisasi");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(40, 60, 220, 30);

        txtLembaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLembagaActionPerformed(evt);
            }
        });
        jPanel3.add(txtLembaga);
        txtLembaga.setBounds(210, 60, 210, 30);

        jLabel13.setText("Nama Peminjam");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(40, 100, 150, 30);

        txtPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeminjamActionPerformed(evt);
            }
        });
        jPanel3.add(txtPeminjam);
        txtPeminjam.setBounds(210, 100, 210, 30);

        jLabel14.setText("No. HP Peminjam");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(40, 140, 150, 30);

        txtHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPActionPerformed(evt);
            }
        });
        jPanel3.add(txtHP);
        txtHP.setBounds(210, 140, 210, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Form Peminjam");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel16);
        jLabel16.setBounds(30, 20, 90, 23);
        jPanel3.add(jSeparator5);
        jSeparator5.setBounds(450, 370, 420, 2);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator6);
        jSeparator6.setBounds(450, 40, 2, 330);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator7);
        jSeparator7.setBounds(870, 40, 2, 330);
        jPanel3.add(jSeparator8);
        jSeparator8.setBounds(450, 40, 420, 2);

        jLabel20.setText("Jumlah Peserta");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(470, 140, 150, 30);

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        jPanel3.add(txtJumlah);
        txtJumlah.setBounds(630, 140, 220, 30);

        jLabel21.setText("Tanggal Selesai");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(470, 220, 150, 30);

        jLabel22.setText("Jam");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(470, 260, 150, 30);

        txtJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamActionPerformed(evt);
            }
        });
        jPanel3.add(txtJam);
        txtJam.setBounds(630, 260, 70, 30);

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Detail Peminjaman");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel27);
        jLabel27.setBounds(460, 20, 110, 23);

        jLabel24.setText("Ruangan / Fasilitas");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(470, 60, 150, 30);

        cboRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Aula 1", "Aula 2", "Aula Mini", "Ruang Rapat" }));
        jPanel3.add(cboRuangan);
        cboRuangan.setBounds(630, 60, 220, 30);

        txtacara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtacaraActionPerformed(evt);
            }
        });
        jPanel3.add(txtacara);
        txtacara.setBounds(630, 100, 220, 30);

        jLabel25.setText("Acara / Kegiatan");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(470, 100, 150, 30);
        jPanel3.add(jSeparator9);
        jSeparator9.setBounds(20, 370, 420, 2);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator11);
        jSeparator11.setBounds(20, 220, 2, 150);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator12);
        jSeparator12.setBounds(440, 220, 2, 150);
        jPanel3.add(jSeparator13);
        jSeparator13.setBounds(20, 220, 420, 2);

        jLabel15.setText("Deskripsi Singkat acara");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(40, 240, 150, 30);

        jLabel17.setText("Tujuan acara");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(40, 320, 150, 30);

        txtTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTujuanActionPerformed(evt);
            }
        });
        jPanel3.add(txtTujuan);
        txtTujuan.setBounds(210, 320, 210, 30);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Deskripsi Peminjaman");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel19);
        jLabel19.setBounds(30, 200, 130, 23);
        jPanel3.add(dtSelesai);
        dtSelesai.setBounds(630, 220, 160, 30);
        jPanel3.add(dtPeminjaman);
        dtPeminjaman.setBounds(630, 180, 160, 30);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Extras-Close-icon.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal);
        btnBatal.setBounds(753, 320, 100, 40);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3floppy-unmount-icon.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan);
        btnSimpan.setBounds(620, 320, 130, 41);

        txaDeskripsi.setColumns(20);
        txaDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txaDeskripsi);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(210, 240, 210, 70);

        jLabel26.setText("Tanggal Peminjaman");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(470, 180, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        getParent().remove(this);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtLembagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLembagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLembagaActionPerformed

    private void txtPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeminjamActionPerformed

    private void txtHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamActionPerformed

    private void txtacaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtacaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtacaraActionPerformed

    private void txtTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTujuanActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        id = "";
        String sql = "INSERT INTO peminjaman SET  "
                + "nama_lembaga ='"+ txtLembaga.getText()+ "',"
                + "nama_peminjam ='"+ txtPeminjam.getText()+ "',"
                + "noHP_Peminjam ='"+ txtHP.getText()+ "',"
                + "deskripsi_acara ='"+ txaDeskripsi.getText()+ "',"
                + "tujuan_acara ='"+ txtTujuan.getText()+ "',"
                + "ruangan_dipinjam ='"+ cboRuangan.getSelectedItem()+ "',"
                + "acara ='"+ txtacara.getText()+ "',"
                + "jumlah_peserta ='"+ txtJumlah.getText()+ "',"
                + "tanggal_peminjaman ='"+ dtPeminjaman.getDate()+ "',"
                + "tanggal_selesai ='"+ dtSelesai.getDate()+ "',"
                + "jam ='"+ txtJam.getText()+ "'";
        Database.eksekusi(sql);
        kosong();
        JOptionPane.showMessageDialog(null, "Data Berhasil di Tambahkan");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cboRuangan;
    private com.toedter.calendar.JDateChooser dtPeminjaman;
    private com.toedter.calendar.JDateChooser dtSelesai;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea txaDeskripsi;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtLembaga;
    private javax.swing.JTextField txtPeminjam;
    private javax.swing.JTextField txtTujuan;
    private javax.swing.JTextField txtacara;
    // End of variables declaration//GEN-END:variables
}
