import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricomrdnsyh
 */
public class PanelUser extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public static String id = "";
    public PanelUser() {
        initComponents();
        tampil("");
    }
    void kosong(){
        txtNama.setText("");
        txtEmail.setText("");
        txtTelepon.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtAlamat.setText("");
        tampil("");
    }
    void  tampil(String filter) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            ResultSet rs = Database.ambilData("SELECT * FROM user " + filter);
            while(rs.next()){
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7)
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error data : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(58, 79, 122));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel2)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(58, 79, 122));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-go-next-icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Form Input");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 10, 70, 23);
        jPanel3.add(jSeparator5);
        jSeparator5.setBounds(20, 200, 420, 2);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator6);
        jSeparator6.setBounds(20, 30, 2, 170);
        jPanel3.add(jSeparator7);
        jSeparator7.setBounds(20, 30, 420, 2);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator8);
        jSeparator8.setBounds(440, 30, 2, 170);
        jPanel3.add(jSeparator9);
        jSeparator9.setBounds(450, 160, 430, 2);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator10);
        jSeparator10.setBounds(450, 30, 2, 130);
        jPanel3.add(jSeparator11);
        jSeparator11.setBounds(450, 30, 430, 2);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator12);
        jSeparator12.setBounds(880, 30, 2, 130);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode User", "Nama User", "Email", "Telepon", "Username", "Password", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(30, 240, 840, 150);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3floppy-unmount-icon.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan);
        btnSimpan.setBounds(450, 170, 120, 50);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Extras-Close-icon.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal);
        btnBatal.setBounds(780, 170, 100, 50);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-trash-full-icon.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnHapus);
        btnHapus.setBounds(670, 170, 110, 50);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save-as-icon.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel3.add(btnUbah);
        btnUbah.setBounds(570, 170, 100, 50);

        jLabel1.setText("Nama User");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(40, 40, 90, 30);
        jPanel3.add(txtEmail);
        txtEmail.setBounds(140, 80, 270, 30);
        jPanel3.add(txtTelepon);
        txtTelepon.setBounds(140, 120, 270, 30);

        jLabel4.setText("Email");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(40, 80, 90, 30);

        jLabel5.setText("Telepon");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 120, 80, 30);

        jLabel6.setText("Username");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 160, 90, 30);
        jPanel3.add(txtPassword);
        txtPassword.setBounds(570, 40, 290, 30);
        jPanel3.add(txtNama);
        txtNama.setBounds(140, 40, 270, 30);

        jLabel7.setText("Password");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(470, 40, 90, 30);

        jLabel8.setText("Alamat");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(470, 80, 90, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(570, 80, 290, 70);
        jPanel3.add(jLabel9);
        jLabel9.setBounds(40, 50, 60, 0);
        jPanel3.add(txtUsername);
        txtUsername.setBounds(140, 160, 270, 30);
        jPanel3.add(jSeparator13);
        jSeparator13.setBounds(20, 400, 860, 2);

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator14);
        jSeparator14.setBounds(20, 230, 2, 170);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data User");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 210, 70, 23);
        jPanel3.add(jSeparator15);
        jSeparator15.setBounds(20, 230, 860, 2);

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator16);
        jSeparator16.setBounds(880, 230, 2, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        getParent().remove(this);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            int i = jTable1.getSelectedRow();
            id = jTable1.getValueAt(i, 0).toString();
            int pesan = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Menghapus Data Ini?");
            if(pesan == JOptionPane.YES_OPTION){
                Database.eksekusi("DELETE FROM user WHERE kode_user = '" + id + "'");
                tampil("");
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Yang DIpilih!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        id = "";
        String sql = "INSERT INTO user SET  "
                + "nama_user ='"+ txtNama.getText()+ "',"
                + "email_user ='"+ txtEmail.getText()+ "',"
                + "telepon_user ='"+ txtTelepon.getText()+ "',"
                + "username_user ='"+ txtUsername.getText()+ "',"
                + "password_user =md5('"+ txtPassword.getText()+ "'),"
                + "alamat_user ='"+ txtAlamat.getText()+ "'";
        Database.eksekusi(sql);
        kosong();
        JOptionPane.showMessageDialog(null, "Data Berhasil di Tambahkan");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        txtNama.setText(jTable1.getValueAt(baris, 1).toString());
        txtEmail.setText(jTable1.getValueAt(baris, 2).toString());
        txtTelepon.setText(jTable1.getValueAt(baris, 3).toString());
        txtUsername.setText(jTable1.getValueAt(baris, 4).toString());
        txtPassword.setText(jTable1.getValueAt(baris, 5).toString());
        txtAlamat.setText(jTable1.getValueAt(baris, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try {
            int i = jTable1.getSelectedRow();
            id = jTable1.getValueAt(i, 0).toString();
            int pesan = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Mengubah Data Ini?");
            if(pesan == JOptionPane.YES_OPTION){
                Database.eksekusi("UPDATE user SET  "
                + "nama_user ='"+ txtNama.getText()+ "',"
                + "email_user ='"+ txtEmail.getText()+ "',"
                + "telepon_user ='"+ txtTelepon.getText()+ "',"
                + "username_user ='"+ txtUsername.getText()+ "',"
                + "password_user =md5('"+ txtPassword.getText()+ "'),"
                + "alamat_user ='"+ txtAlamat.getText()+ "'" 
                + "WHERE kode_user= '" + id + "'");
                kosong();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Yang DIpilih!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
